import './globals.css';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });
import Navbar from '../components/Navbar/index';
import Footer from '../components/Footer/Footer';

export const metadata = {
  title: 'Medium Clone',
  description: 'Generated by create next app For Medium Clone',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
